// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruckService.Data;

#nullable disable

namespace TruckService.Migrations
{
    [DbContext(typeof(TruckDbContext))]
    [Migration("20251125225052_SyncModel")]
    partial class SyncModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("TruckService.Data.DeliveryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossEarnings")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoadByTypeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetProfit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OperatingCost")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecyclerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TruckId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("deliveries");
                });

            modelBuilder.Entity("TruckService.Data.TruckEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CapacityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentLoadByTypeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalEarnings")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
