// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RecyclingPlantService.Data.Migrations
{
    [DbContext(typeof(RecyclingPlantDbContext))]
    partial class RecyclingPlantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RecyclingPlantService.Data.PlantDelivery", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid");
                    b.Property<Guid>("TruckId").HasColumnType("uuid");
                    b.Property<Guid>("PlayerId").HasColumnType("uuid");
                    b.Property<int>("GlassCount").HasColumnType("integer");
                    b.Property<int>("MetalCount").HasColumnType("integer");
                    b.Property<int>("PlasticCount").HasColumnType("integer");
                    b.Property<decimal>("GrossEarnings").HasColumnType("numeric");
                    b.Property<decimal>("OperatingCost").HasColumnType("numeric");
                    b.Property<decimal>("NetEarnings").HasColumnType("numeric");
                    b.Property<DateTimeOffset>("DeliveredAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");

                    b.HasKey("Id");
                    b.ToTable("plant_deliveries");
                });

            modelBuilder.Entity("RecyclingPlantService.Data.PlayerEarnings", b =>
                {
                    b.Property<Guid>("PlayerId").HasColumnType("uuid");
                    b.Property<decimal>("TotalEarnings").HasColumnType("numeric");
                    b.Property<int>("DeliveryCount").HasColumnType("integer");
                    b.Property<decimal>("AverageEarnings").HasColumnType("numeric");
                    b.Property<DateTimeOffset>("LastUpdated").HasColumnType("timestamp with time zone");

                    b.HasKey("PlayerId");
                    b.ToTable("player_earnings");
                });
#pragma warning restore 612, 618
        }
    }
}