{
 "title": "Trucks",
 "tags": [ "truck" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Truck Current Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "truck_current_load_bottles{job=\"truckservice\"} * on(truck_id) group_left(truck_name) (truck_active_state{job=\"truckservice\"} == 1)",
     "legendFormat": "{{ truck_name }}"
    }
   ]
  },
  {
   "title": "Truck Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "truck_capacity_bottles{job=\"truckservice\"} * on(truck_id) group_left(truck_name) (truck_active_state{job=\"truckservice\"} == 1)",
     "legendFormat": "{{ truck_name }}"
    }
   ]
  },
  {
   "title": "Total Deliveries Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by (truck_name) (increase(deliveries_processed_deliveries_total{job=\"recyclingplantservice\",truck_name!=\"\"}[5m]) and (timestamp(deliveries_processed_deliveries_total{job=\"recyclingplantservice\",truck_name!=\"\"}) > (time() - 30)))",
     "legendFormat": "{{truck_name}}"
    }
   ]
  }
 ]
}