// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using RecyclerService.Data;

#nullable disable

namespace RecyclerService.Migrations
{
    [DbContext(typeof(RecyclerDbContext))]
    partial class RecyclerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RecyclerService.Models.Recycler", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<string>("Name").HasColumnType("character varying(200)").HasMaxLength(200);
                b.Property<int>("Capacity").HasColumnType("integer");
                b.Property<int>("CurrentLoad").HasColumnType("integer").HasDefaultValue(0);
                b.Property<string>("Location").HasColumnType("text");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasDefaultValueSql("now()");
                b.Property<DateTimeOffset?>("LastEmptiedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("CurrentLoad");
                b.ToTable("Recyclers");
            });

            modelBuilder.Entity("RecyclerService.Models.Visitor", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<Guid>("RecyclerId").HasColumnType("uuid");
                b.Property<string>("VisitorType").HasColumnType("character varying(50)").HasMaxLength(50);
                b.Property<int>("Bottles").HasColumnType("integer");
                b.Property<DateTimeOffset>("ArrivedAt").HasColumnType("timestamp with time zone").HasDefaultValueSql("now()");
                b.HasKey("Id");
                b.HasIndex("RecyclerId");
                b.ToTable("Visitors");
            });
#pragma warning restore 612, 618
        }
    }
}